### ISSUE TITLE
iOS build failed with no helpful error messages

### ISSUE THREAD

**Issue by Sofianio** [hansemannn/titanium-firebase-analytics#51]
- I Added the firebase.core module v2.2.0
- I put `GoogleService-Info.plist` in `app/assets/iphone`
- I Added firebase.analytics module v1.4.1
- And I called the module from within the app

The app doesn't even build in iOS !!!
Here's what I get:
```
...
[INFO]  Invoking xcodebuild
[ERROR] ** BUILD FAILED **
[ERROR] The following build commands failed:
[ERROR]         Ld /Users/Me/Documents/Appcelerator_Studio_Workspace/MyApp/build/iphone/build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal x86_64
[ERROR] (1 failure)
```
I even tried older versions core 2.0.0 with analytics 1.4.0 with no success

Please help, thanks.

**Comment by Sofianio** [comment]
Hello?

**Comment by redouaneboudella** [comment]
So i dug a little deeper, it seems that since we re using this module with the googlesignin module, that some dependencies on google'sdks are conflicting ...

Here is a stackoverflow question pertaining to the same issue 
[link](https://stackoverflow.com/questions/54629936/firebase-google-signin-module-conflicting-in-appcelerator#)

Here is the same issue discussed for a native app when sdks are included without cocoapods
[Link](https://stackoverflow.com/questions/41217839/duplicate-symbols-when-integrating-firebase-and-google-sign-in-sdks-manually-wit)

well cocoapods is quiet handy to handle symbol duplication ...

It seems like a dead end for now @hansemannn , any thoughts

Many thanks

**Comment by hansemannn** [comment]
You can remove the duplicate Google utils framework and it should work. Please advise the community for details.

**Comment by redouaneboudella** [comment]
Thanks @hansemannn for the quick reply (as always :) )

When you say delete the framework do you mean from the generated zip module or from the sources and then try to build it again ?

**Comment by redouaneboudella** [comment]
@hansemannn 
There is actually a note on the Firebase-Core module that mentions the solution, it would ve been of a good use to add the note on the googlesignin module also.
The note goes as follows:


If you are also using Ti.GoogleSignIn you will probably have a duplicate symbols error. Both Ti.GoogleSignIn and this module share some common dependencies. In order to solve this conflict, remove the GTMSessionFetcher.framework and GoogleToolboxForMac.framework files from <YOUR_PROJECT_DIR>/modules/iphone/firebase.core/<VERSION>/platform and rebuild your app.

**Comment by hansemannn** [comment]
@redouaneboudella Feel free to do a pull request on the Google Sign In repo. If you don't how to do that, google "github pull requests".
